### ISSUE TITLE
First-time install and startup

### ISSUE THREAD

**Issue by K-Mistele** [Michael-N/Certamen#3]
Couple of issues here: 
First, when running `npm run setup`, multiple unmet dependencies: 

![unmet-dependencies](https://user-images.githubusercontent.com/18430555/29251263-ed58f540-801f-11e7-87d1-9a2789c7326d.PNG)
 
Secondly, what's the deal with gulp? How's that work?
Thirdly, on trying to access http://localhost:8081, this error throws: `Cannot GET /`, detailed console message below:
![console-err](https://user-images.githubusercontent.com/18430555/29251290-40b38f66-8020-11e7-90c9-e838d2a6005f.PNG)

**Comment by K-Mistele** [comment]
Fix: update readme.md to reflect proper install process and necessary dependencies (react)

**Comment by Michael-Naguib** [comment]
I modified it so the react deps will be installed automatically properly as part of the npm install

**Comment by Michael-Naguib** [comment]
Readme.md updated
